### ISSUE TITLE
Jaguar wheel encoder 

### ISSUE THREAD

**Issue by kevinlisun** [TRI-jaguar4x4/jaguar4x4_base#1]
Hi Guys

It is really hard to find people using this robot. Recently, I got a Jaguar4x4 robot with an arm. While I got some issues, may I ask here?

The model I got is a 2014 version (latter) and I am using the official repository https://github.com/gitdrrobot/jaguar4x4_2014 

1) I cannot read the motor encoder i.e. positions and velocities. They are all zeros. I am wondering whether you also met this issue?

![image](https://user-images.githubusercontent.com/6146880/68721719-3f6ee480-05ab-11ea-8a86-a7fa0ca65b16.png)

2) Your ROS2-based implementation looks very fancy and easier to use. Is there a reason that you removed two wheels? Will it work with the original 4 wheels' model?

Many Thanks,
Kevin

**Comment by clalancette** [comment]
I'm honestly not sure why you are getting all zeros from the original code.  We only ran that code very briefly when we first got the vehicle, and then we did the ROS 2 implementation instead.

As far as the wheels are concerned, the project we were working on at the time only needed two wheels for differential drive.  That's why we removed the other two wheels.  Things should mostly work with the 4 wheels, though you may have to do some additional development to actually send separate commands to the 4 wheels independently (if that's what you want to do).  I'll close this issue out for now, but please feel free to keep commenting if you'd like a bit more information.
